name: Deploy AKS

on:
  push:
    branches:
      - sandbox

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  RESOURCE_GROUP: ${{ github.head_ref || github.ref_name }} 
  AKS_CLUSTER_NAME: ${{ github.head_ref || github.ref_name }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy-bicep:
    #runs-on: ubuntu-latest
    # Added self hosted agent
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: >
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
            "subscriptionId": "1d2e52d9-93e9-4ee4-b2c6-badd357535e3"
          }

    - name: Set up Bicep
      run: |
        az bicep install
        az bicep upgrade


    - name: Deploy Bicep template
      run: |
        az deployment group create --resource-group $RESOURCE_GROUP --template-file ./aks.bicep --parameters aksClusterName=$AKS_CLUSTER_NAME clientId=$AZURE_CLIENT_ID clientSecret=$AZURE_CLIENT_SECRET sshPublicKey="$SSH_KEY" --mode Complete